#include "myCombobox.h"

MyCombobox::MyCombobox()
{
    this->setPlaceholderText(tr("Choose key"));
    this->addItem("A");
    this->addItem("B");
    this->addItem("C");
    this->addItem("D");
    this->addItem("E");
    this->addItem("F");
    this->addItem("G");
    this->addItem("H");
    this->addItem("I");
    this->addItem("J");
    this->addItem("K");
    this->addItem("L");
    this->addItem("M");
    this->addItem("N");
    this->addItem("O");
    this->addItem("P");
    this->addItem("Q");
    this->addItem("R");
    this->addItem("S");
    this->addItem("T");
    this->addItem("U");
    this->addItem("V");
    this->addItem("W");
    this->addItem("X");
    this->addItem("Y");
    this->addItem("Z");
    this->addItem("0");
    this->addItem("1");
    this->addItem("2");
    this->addItem("3");
    this->addItem("4");
    this->addItem("5");
    this->addItem("6");
    this->addItem("7");
    this->addItem("8");
    this->addItem("9");
    this->addItem("F1");
    this->addItem("F2");
    this->addItem("F3");
    this->addItem("F4");
    this->addItem("F5");
    this->addItem("F6");
    this->addItem("F7");
    this->addItem("F8");
    this->addItem("F9");
    this->addItem("F10");
    this->addItem("F11");
    this->addItem("F12");
}
